---
apiVersion: v1
kind: Namespace
metadata:
  name: "ci-infra-dns-monitor"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: system:openshift:scc:anyuid
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- kind: ServiceAccount
  name: default
  namespace: ci-infra-dns-monitor
---
# Allow pods to run with hostNetwork: true
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:scc:privileged
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: default
  namespace: ci-infra-dns-monitor
- kind: ServiceAccount
  name: deployer
  namespace: ci-infra-dns-monitor
---
# Allow pods to run oc describe
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-cluster-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-reader
subjects:
- kind: ServiceAccount
  name: default
  namespace: ci-infra-dns-monitor
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ci-infra-dns-monitor
  namespace: ci-infra-dns-monitor
  labels:
    k8s-app: ci-infra-dns-monitor
spec:
  selector:
    matchLabels:
      name: ci-infra-dns-monitor
  template:
    metadata:
      labels:
        name: ci-infra-dns-monitor
    spec:
      tolerations:
      - key: node-role.kubernetes.io/ci-builds-worker
        operator: Exists
      - key: node-role.kubernetes.io/ci-tests-worker
        operator: Exists
      - key: node-role.kubernetes.io/ci-longtests-worker
        operator: Exists
      - key: node-role.kubernetes.io/ci-prowjobs-worker
        operator: Exists
      securityContext:
        capabilities:
          add:
          - NET_RAW
      containers:
      - name: dns-monitor
        image: quay.io/jupierce/infra-dns-monitor:prod
        imagePullPolicy: Always
        securityContext:
          privileged: true
          runAsUser: 0
          capabilities:
            add:
            - NET_RAW
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /tmp/creds/openshift-gce-devel-kettle.json
        resources:
          limits:
            memory: 400Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: creds
          mountPath: "/tmp/creds"
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: creds
        secret:
          secretName: openshift-gce-devel-kettle
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ci-infra-dns-monitor-hostnetwork
  namespace: ci-infra-dns-monitor
  labels:
    k8s-app: ci-infra-dns-monitor-hostnetwork
spec:
  selector:
    matchLabels:
      name: ci-infra-dns-monitor-hostnetwork
  template:
    metadata:
      labels:
        name: ci-infra-dns-monitor-hostnetwork
    spec:
      hostNetwork: True
      tolerations:
      - key: node-role.kubernetes.io/ci-builds-worker
        operator: Exists
      - key: node-role.kubernetes.io/ci-tests-worker
        operator: Exists
      - key: node-role.kubernetes.io/ci-longtests-worker
        operator: Exists
      - key: node-role.kubernetes.io/ci-prowjobs-worker
        operator: Exists
      containers:
      - name: dns-monitor
        image: quay.io/jupierce/infra-dns-monitor:prod
        imagePullPolicy: Always
        securityContext:
          privileged: true
          runAsUser: 0
          capabilities:
            add:
            - NET_RAW
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: TEST_VARIANT
          value: "-hostNetwork"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /tmp/creds/openshift-gce-devel-kettle.json
        resources:
          limits:
            memory: 400Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: creds
          mountPath: "/tmp/creds"
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: creds
        secret:
          secretName: openshift-gce-devel-kettle
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ci-infra-dns-monitor-nodedns
  namespace: ci-infra-dns-monitor
  labels:
    k8s-app: ci-infra-dns-monitor-nodedns
spec:
  selector:
    matchLabels:
      name: ci-infra-dns-monitor-nodedns
  template:
    metadata:
      labels:
        name: ci-infra-dns-monitor-nodedns
    spec:
      tolerations:
      - key: node-role.kubernetes.io/ci-builds-worker
        operator: Exists
      - key: node-role.kubernetes.io/ci-tests-worker
        operator: Exists
      - key: node-role.kubernetes.io/ci-longtests-worker
        operator: Exists
      - key: node-role.kubernetes.io/ci-prowjobs-worker
        operator: Exists
      securityContext:
        capabilities:
          add:
          - NET_RAW
      dnsPolicy: Default
      containers:
      - name: dns-monitor
        image: quay.io/jupierce/infra-dns-monitor:prod
        imagePullPolicy: Always
        securityContext:
          privileged: true
          runAsUser: 0
          capabilities:
            add:
            - NET_RAW
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: TEST_VARIANT
          value: "-nodedns"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /tmp/creds/openshift-gce-devel-kettle.json
        resources:
          limits:
            memory: 400Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: creds
          mountPath: "/tmp/creds"
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: creds
        secret:
          secretName: openshift-gce-devel-kettle
