---
apiVersion: v1
kind: Namespace
metadata:
  name: "ephemeral-node-dns-monitor"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: system:openshift:scc:anyuid
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- kind: ServiceAccount
  name: default
  namespace: ephemeral-node-dns-monitor
---
# Allow pods to run with hostNetwork: true
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:scc:privileged
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: default
  namespace: ephemeral-node-dns-monitor
- kind: ServiceAccount
  name: deployer
  namespace: ephemeral-node-dns-monitor
---
# Allow pods to run oc describe
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-cluster-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-reader
subjects:
- kind: ServiceAccount
  name: default
  namespace: ephemeral-node-dns-monitor
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ephemeral-node-dns-monitor
  namespace: ephemeral-node-dns-monitor
  labels:
    k8s-app: ephemeral-node-dns-monitor
spec:
  selector:
    matchLabels:
      name: ephemeral-node-dns-monitor
  template:
    metadata:
      labels:
        name: ephemeral-node-dns-monitor
    spec:
      tolerations:
      - key: node-role.kubernetes.io/ci-builds-worker
        operator: Exists
      - key: node-role.kubernetes.io/ci-tests-worker
        operator: Exists
      - key: node-role.kubernetes.io/ci-longtests-worker
        operator: Exists
      - key: node-role.kubernetes.io/ci-prowjobs-worker
        operator: Exists
      securityContext:
        capabilities:
          add:
          - NET_RAW
      containers:
      - name: dns-monitor
        image: quay.io/jupierce/infra-dns-monitor:ephemeral-node
        imagePullPolicy: Always
        securityContext:
          privileged: true
          runAsUser: 0
          capabilities:
            add:
            - NET_RAW
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          limits:
            memory: 400Mi
          requests:
            cpu: 100m
            memory: 200Mi
      terminationGracePeriodSeconds: 30
